### ISSUE TITLE
(ddu) package verification problem

### ISSUE THREAD

**Issue by RedBaron2** [tunisiano187/Chocolatey-packages#19]
@tunisiano187 
**Describe the bug**
This has to do with the [gist](https://gist.github.com/b99416e5d5eba8efc295f9ff16044704) of not being able to download or create the SSL/TLS connection.

This has to due with the **_wagnardsoft_** [server](https://www.ssllabs.com/ssltest/analyze.html?d=www.wagnardsoft.com&s=51.161.33.81&latest) needing to use a referrer to download the file [now](https://ci.appveyor.com/project/RBZ/development/builds/33961656).

You can take a look at my update to the ddu package [here](https://github.com/RedBaron2/development/tree/RedBaron2-ddu-rbz/automatic/ddu). I can also submit a PR if you would like that option.

**Comment by tunisiano187** [comment]
@all-contributors please add @RedBaron2 for bug

**Comment by tunisiano187** [comment]
Pushed, waiting for the result before closing, thank you for you help.
Don't hesitate next time to send a pull request, just pay attention to keep the same logic for the automatic update as i do .
I've added you in the contributors, don't hesitate to tell me if you want to be removed.

Have a nice day

**Comment by RedBaron2** [comment]
@tunisiano187 
You do realize that that referrer `t=xxxx` changes with every release, right?

**Comment by tunisiano187** [comment]
Yes, i'll try to find a way to get it
Thank you

**Comment by tunisiano187** [comment]
Done,the referer link will be changed everytime now
