### ISSUE TITLE
[Bug] Remove-empty-directory fails install

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/Chocolatey-packages#22]
**Describe the bug**
When trying to install the process don't succeed

**To Reproduce**
Try to install 

**Expected behavior**
Success

**Additional context**
May need AHK

**Comment by tunisiano187** [comment]
Working on it

**Comment by tunisiano187** [comment]
https://chocolatey.org/packages/remove-empty-directories/2.2

**Comment by tunisiano187** [comment]
Tryied the Portable version

**Comment by tunisiano187** [comment]
Passed

**Comment by Jeroen52** [comment]
It seems that this is still the issue, chocolatey installs the source code under `C:\ProgramData\chocolatey\lib\remove-empty-directories\tools` but it doesn't compile it.

**Comment by tunisiano187** [comment]
Sorry for my mistake.
I've pushed a version 2.2.0.1 to correct this one.
Thank you for the followup.

**Comment by Jeroen52** [comment]
Thanks for the quick fix, and everyone makes mistakes.
