### ISSUE TITLE
[Bug] broken error handling in keepass-plugin-webautotype

### ISSUE THREAD

**Issue by donestefan** [tunisiano187/Chocolatey-packages#2837]
**Describe the bug**

Seems like the error handling is broken for cases when chocolatey is used to install the plugin over an existing installation.

```
2020-08-13 14:33:32,608 3508 [INFO ] - VERBOSE: Removing any plugin with name WebAutoType.plgx in C:\Program Files (x86)\KeePass Password Safe 2\ to prevent duplicate plugin loading
2020-08-13 14:33:32,635 3508 [ERROR] - ERROR: Cannot compare "WebAutoType.plgx" because it is not IComparable.
```

Probably caused by line 64 and 66 in https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/keepass-plugin-webautotype/tools/chocolateyInstall.ps1

**To Reproduce**
1. install the plugin outside of chocolatey
2. run ` choco install keepass-plugin-webautotype`
3. See error on command line and in installation log

**Desktop (please complete the following information):**
 - OS: Windows 10
 - chocolatey 0.10.15
 - keepass-plugin-webautotype 6.4.0

**Comment by tunisiano187** [comment]
OK, missing count...
Thank you
It should be OK for the next version.
