### ISSUE TITLE
64 bit Winmerge installs per user

### ISSUE THREAD

**Issue by SamHills** [tunisiano187/Chocolatey-packages#2868]
The current version (2.16.8) of the Winmerge installer installs the per-user version of 64-bit Winmerge instead of the regular (all users) version.

To see the bug: look at the installer script.  Notice that the 64-bit command installs the per-user version (WinMerge-2.16.8-x64-PerUser-Setup.exe)  whereas the 32-bit command installs the all-users version (WinMerge-2.16.8-Setup.exe).

**Comment by tunisiano187** [comment]
OK, solved for the following version and pushed an intermediate one
