### ISSUE TITLE
[Bug] DDU leaving files from old versions and multiple shims.

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [tunisiano187/Chocolatey-packages#2874]
**Describe the bug**
The DDU package does not clean up old versions on upgrade. This leaves extra files on the filesystem and extra shims in the bin directory. 

**To Reproduce**
1. Install a previous version of DDU
2. Upgrade to the latest version of DDU. 

**Expected behavior**
After upgrade, the only files and shims are from the currently installed version.

**Screenshots**
![image](https://user-images.githubusercontent.com/38865330/93654888-d2578700-f9e5-11ea-9da9-feea90d02112.png)
![image](https://user-images.githubusercontent.com/38865330/93654897-e13e3980-f9e5-11ea-9788-64f98776681b.png)

**Desktop:**
 - OS: Windows 10 2004 x64
 - Version: 18.0.3.2 and older versions as well

**Comment by tunisiano187** [comment]
OK, solved for the next release.

Thank you for the information

**Comment by AeliusSaionji** [comment]
I'm still getting this!

![image](https://user-images.githubusercontent.com/4342746/155257295-d688d4f3-e44b-4397-ba92-de15d5a35aae.png)
