### ISSUE TITLE
[Version mismatch] Bonjour

### ISSUE THREAD

**Issue by ianc1215** [tunisiano187/Chocolatey-packages#2916]
**Describe the bug**
The version of Bonjour that is installed from the Choco package is 2.0.2 from 2010. The current available version of Bonjour that can be installed is 3.1.0.1. No sure if it matters but it has to be extracted from the iTunes install files. No standalone version exists that I am aware of.

**To Reproduce**
1. Search for Bonjour on Chocolately repos
2. Install Bonjour, posted version says 3.1.0.2 but this is not real.
3. Navigate to C:/Program Files/Bonjour/mdnsNSP.dll and check the version. It will say 2.0.2 from file date May 2010.

**Expected behavior**
The version of the package does not match what is actually installed, this needs corrected.

**Comment by tunisiano187** [comment]
Hello,
that's what i'm doing, getting the file un compressing it, and installing the integrated MSI.
The version number come from the installer inside the exe file.

I don't see any trouble
