### ISSUE TITLE
[Bug] Hashes do not match on boinc_7.16.16_windows_x86_64.exe

### ISSUE THREAD

**Issue by edgeman16** [tunisiano187/Chocolatey-packages#2918]
**Describe the bug**
boinc package fails to install due to checksum mismatch

**To Reproduce**
1. choco install boinc

**Screenshots**
boinc v7.16.16 [Approved]
boinc package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Error - hashes do not match. Actual value was '3F52C167449259EC038DA180D16E5E9178B5E2E24730F2A23E1D85AC8DA4EA54'.
Downloading boinc
  from 'https://boinc.berkeley.edu/dl/boinc_7.16.16_windows_x86_64.exe'
Progress: 100% - Completed download of C:\Users\Edgeman\AppData\Local\Temp\chocolatey\boinc\7.16.16\boinc_7.16.16_windows_x86_64.exe (12.84 MB).
Download of boinc_7.16.16_windows_x86_64.exe (12.84 MB) completed.
Error - hashes do not match. Actual value was '3F52C167449259EC038DA180D16E5E9178B5E2E24730F2A23E1D85AC8DA4EA54'.
ERROR: Checksum for 'C:\Users\Edgeman\AppData\Local\Temp\chocolatey\boinc\7.16.16\boinc_7.16.16_windows_x86_64.exe' did not meet '4542e15073b7bd27c08ab0e9d8238c83e49980c94e4b34ebde07d6b5d7246bec' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The install of boinc was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\boinc\tools\chocolateyInstall.ps1'.
 See log for details.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 2004
 - Version boinc v7.16.16

**Comment by tunisiano187** [comment]
I'll take a look tomorrow, i think the newer version is waiting for moderation

**Comment by tunisiano187** [comment]
Correction pushed

**Comment by edgeman16** [comment]
Is there something else that needs to be done? I'm still having the exact same issue on "choco install boinc"

**Comment by tunisiano187** [comment]
Se nerf to sait for approval
