### ISSUE TITLE
[Bug] Incorrect checksums for the latest p4merge install

### ISSUE THREAD

**Issue by snolan-uturn** [tunisiano187/Chocolatey-packages#2921]
**Describe the bug**
The checksums for the current version of p4merge are incorrect, therefore installing p4merge fails.

**To Reproduce**
1. run `choco install p4merge`
2. install fails

**Expected behavior**
p4merge is installed.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The checksums in https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/p4merge/tools/chocolateyinstall.ps1 are wrong.
The correct checksums here:
https://cdist2.perforce.com/perforce/r20.2/bin.ntx86/SHA256SUMS https://cdist2.perforce.com/perforce/r20.2/bin.ntx64/SHA256SUMS
are:
$checksum         = '9f3c000f5bee0937e68034ab2bcc43972ce6d358a40ceaff1d6e0b9ef30e6c1f'
$checksum64       = '3484261969c0295fe6908efbe911b63a938d9f2cfdb5888d6670a676e4b9f20b'

**Comment by tunisiano187** [comment]
Indeed, i've pushed an update on my git, the newer version will be available ASAP
Thank you!
