### ISSUE TITLE
Version 7.16.16 is not a stable release

### ISSUE THREAD

**Issue by flammobammo** [tunisiano187/Chocolatey-packages#2942]
Version 7.16.16 is not a stable release as per what is available at:
https://boinc.berkeley.edu/download.php

Refer:
https://boinc.berkeley.edu/wiki/Release_Notes

7.16.16 must be a beta version available for test purposes only. There is no evidence to suggest it is not a beta.

**Comment by tunisiano187** [comment]
i'm currently searching why they have that version available on the repository and how i can manage these.
is it blocking anything? (it's working on my side)
