### ISSUE TITLE
New installer for Fing? /S not supported?

### ISSUE THREAD

**Issue by AIVAS001** [tunisiano187/Chocolatey-packages#2945]
New installer for Fing? /S not supported?

CONSOLE
=======
> You have fing v2.3.1 installed. Version 2.4.1 is available based on your source(s).
> Progress: Downloading fing 2.4.1... 100%
> 
> fing v2.4.1 [Approved]
> fing package files upgrade completed. Performing other installation steps.
> Downloading fing
>   from 'https://get.fing.com/fing-desktop-releases/windows/Fing.exe'
> Progress: 100% - Completed download of C:\Users\rjp\AppData\Local\Temp\chocolatey\fing\2.4.1\Fing.exe (75.01 MB).
> Download of Fing.exe (75.01 MB) completed.
> Hashes match.
> Installing fing...
> ERROR: Running ["C:\Users\rjp\AppData\Local\Temp\chocolatey\fing\2.4.1\Fing.exe" /S ] was not successful. Exit code was '1'. > See log for possible error messages.
> The upgrade of fing was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\fing\tools\chocolateyinstall.ps1'.
>  See log for details.
> 
> Chocolatey upgraded 0/1 packages. 1 packages failed.

CHOCOLATEY LOG
============

> 2020-12-18 16:50:28,153 12496 [DEBUG] - Running Start-ChocolateyProcessAsAdmin -validExitCodes '0' -workingDirectory 'C:\Users\rjp\AppData\Local\Temp\chocolatey\fing\2.4.1' -statements '/S ' -exeToRun 'C:\Users\rjp\AppData\Local\Temp\chocolatey\fing\2.4.1\Fing.exe' 
> 2020-12-18 16:50:28,156 12496 [DEBUG] - Unable to use current location for Working Directory. Using Cache Location instead.
> 2020-12-18 16:50:28,179 12496 [DEBUG] - Test-ProcessAdminRights: returning True
> 2020-12-18 16:50:28,193 12496 [DEBUG] - Elevating permissions and running ["C:\Users\rjp\AppData\Local\Temp\chocolatey\fing\2.4.1\Fing.exe" /S ]. This may take a while, depending on the statements.
> 2020-12-18 16:50:32,427 12496 [DEBUG] - Command ["C:\Users\rjp\AppData\Local\Temp\chocolatey\fing\2.4.1\Fing.exe" /S ] exited with '1'.
> 2020-12-18 16:50:32,464 12496 [ERROR] - ERROR: Running ["C:\Users\rjp\AppData\Local\Temp\chocolatey\fing\2.4.1\Fing.exe" /S ] was not successful. Exit code was '1'. See log for possible error messages.
> 2020-12-18 16:50:32,468 12496 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\fing\tools\chocolateyinstall.ps1' -installArguments '' -packageParameters '''] exited with '1'.
> 2020-12-18 16:50:32,471 12496 [DEBUG] - Calling command ['"C:\WINDOWS\System32\shutdown.exe" /a']
> 2020-12-18 16:50:32,513 12496 [DEBUG] - Command ['"C:\WINDOWS\System32\shutdown.exe" /a'] exited with '1116'
> 2020-12-18 16:50:32,555 12496 [DEBUG] - Capturing package files in 'C:\ProgramData\chocolatey\lib\fing'
> 2020-12-18 16:50:32,557 12496 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\fing\fing.nupkg'
  with checksum 'F17DCCAC50AE4486F6E5977CBC7D2238'
> 2020-12-18 16:50:32,558 12496 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\fing\fing.nuspec'
  with checksum '8D29A4E3C82E1704B7DD72A2E7F9B4DA'
> 2020-12-18 16:50:32,560 12496 [DEBUG] -  Found 'C:\ProgramData\chocolatey\lib\fing\tools\chocolateyinstall.ps1'
  with checksum 'B33434683590DD1687A14355DCD05EA0'
> 2020-12-18 16:50:32,572 12496 [DEBUG] - Attempting to create directory "C:\ProgramData\chocolatey\.chocolatey\fing.2.4.1".
> 2020-12-18 16:50:32,576 12496 [DEBUG] - There was no original file at 'C:\ProgramData\chocolatey\.chocolatey\fing.2.4.1\.files'
> 2020-12-18 16:50:32,579 12496 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\fing.2.4.1\.arguments".
> 2020-12-18 16:50:32,580 12496 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\fing.2.4.1\.extra".
> 2020-12-18 16:50:32,581 12496 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\fing.2.4.1\.version".
> 2020-12-18 16:50:32,583 12496 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\fing.2.4.1\.sxs".
> 2020-12-18 16:50:32,583 12496 [DEBUG] - Attempting to delete file "C:\ProgramData\chocolatey\.chocolatey\fing.2.4.1\.pin".
> 2020-12-18 16:50:32,586 12496 [DEBUG] - Sending message 'HandlePackageResultCompletedMessage' out if there are subscribers...
> 2020-12-18 16:50:32,588 12496 [ERROR] - The upgrade of fing was NOT successful.
> 2020-12-18 16:50:32,592 12496 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\fing\tools\chocolateyinstall.ps1'.
 See log for details.
> 2020-12-18 16:50:32,596 12496 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib\fing'
 to 'C:\ProgramData\chocolatey\lib-bad\fing'
> 2020-12-18 16:50:34,604 12496 [DEBUG] - Attempting rollback
> 2020-12-18 16:50:34,605 12496 [DEBUG] - Moving 'C:\ProgramData\chocolatey\lib-bkp\fing'
 to 'C:\ProgramData\chocolatey\lib\fing'
> 2020-12-18 16:50:36,616 12496 [DEBUG] - Attempting to delete file "C:\Users\rjp\AppData\Local\NuGet\Cache\fing.2.4.1.nupkg".
> 2020-12-18 16:50:36,628 12496 [WARN ] - 
Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 2020-12-18 16:50:36,630 12496 [INFO ] - 
> 2020-12-18 16:50:36,632 12496 [ERROR] - Failures
> 2020-12-18 16:50:36,634 12496 [ERROR] -  - fing (exited 1) - Error while running 'C:\ProgramData\chocolatey\lib\fing\tools\chocolateyinstall.ps1'.
 See log for details.
> 2020-12-18 16:50:36,638 12496 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
> 2020-12-18 16:50:36,654 12496 [DEBUG] - Exiting with 1

**Comment by tunisiano187** [comment]
Hello,
I don't have any error on my side.
Can you tell me if you have already installed it ?
is it to update if ?

Thank you.

**Comment by tunisiano187** [comment]
Oh just saw it in your log, sorry, i'll try to install it that way

**Comment by tunisiano187** [comment]
OK, it's solved here, just need to wait for the update
