### ISSUE TITLE
[Bug] bad checksum for p4merge r20.3

### ISSUE THREAD

**Issue by zb140** [tunisiano187/Chocolatey-packages#2960]
**Describe the bug**
Because Perforce likes to change their installer binaries without bumping the version, the checksums for p4merge are out of sync again.

**Additional context**
The p4v chocolatey package just downloads the checksums at install time (see here: https://github.com/ripclawffb/chocolatey-p4v/blob/master/tools/chocolateyinstall.ps1#L6).  It may be worth considering a similar solution for p4merge.

**Comment by tunisiano187** [comment]
Solved
