### ISSUE TITLE
[Bug] Installer arguments for p4merge newer than 2020.1 have changed

### ISSUE THREAD

**Issue by zb140** [tunisiano187/Chocolatey-packages#2961]
**Describe the bug**
Installing p4merge newer than 2020.1 actually installs all of p4v.

**Expected behavior**
Only p4merge should be installed.  The other features should not be.

**Additional context**
Apparently newer versions of the p4v installer have completely changed the arguments to pass to the installer.  Here's a link that explains the new arguments: https://community.perforce.com/s/article/17304

**Comment by tunisiano187** [comment]
I've updated the installation script, i hope it will be OK on the next update

**Comment by zb140** [comment]
@tunisiano187 Thanks for the quick change!  I think it should actually be `REMOVEAPPS=P4V,P4ADMIN,P4` though -- the way it currently is, P4Merge will not be installed, but for this package it should be the _only_ package installed.

**Comment by tunisiano187** [comment]
Oups, indeed, correction sent.
Thank you

**Comment by zb140** [comment]
Excellent, thanks!
