### ISSUE TITLE
[Update Request] jbs

### ISSUE THREAD

**Issue by paradonym** [tunisiano187/Chocolatey-packages#2979]
<---
Type the name of the package in the title
Before submitting please check if the package is in this git
--->

**Version requested**
Give the version that should be available.
Download Link update: https://dl.johnsadventures.com/SwitcherSetupCurrent.exe

this is a link for the most recent version to avoid updating the package every time jbs is updated. To make the package jbs self-updating.

**Comment by tunisiano187** [comment]
The chocolatey package needs to be updated to avoid checksum errors.
so i still need to update it each time.
