### ISSUE TITLE
install scratch goes to error

### ISSUE THREAD

**Issue by help-CD09** [tunisiano187/Chocolatey-packages#2980]
download works correctly, but "scratch" doesn't install, as if there was a wrong filename
**To Reproduce**
1. Go to 'powershell as administrator'
2. Click on 'choco install scratch -y'
3. See error

**Expected behavior**
expect that scratch installs correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 

**Additional context**
The install of scratch was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\scratch\tools\chocolateyinstall.ps1'.
 See log for details.

**Comment by tunisiano187** [comment]
Hello,
can you send me the logs ?
Thank you.

**Comment by tunisiano187** [comment]
yes
