### ISSUE TITLE
rufus.install - Rufus (Install appx Windows 10)

### ISSUE THREAD

**Issue by xmha97** [tunisiano187/Chocolatey-packages#2985]
From now on, the Rufus AppX packages are only available in the Microsoft Store and no longer will upload in GitHub.
https://github.com/pbatard/rufus/issues/1735#issuecomment-846423549
https://www.microsoft.com/en-us/p/rufus/9pc3h3v7q9ch
To download the AppX file you should use the following website:
https://store.rg-adguard.net/

**Comment by xmha97** [comment]
Download [Rufus-3.14.AppxBundle](https://www.dropbox.com/s/2ic7tvwr4hcr9ox/Rufus-3.14.AppxBundle?dl=1)

**Comment by tunisiano187** [comment]
I connot use a link that's not official dropbox for example, and it seems that there isn't any solution to automate it anymore... :'(
