### ISSUE TITLE
Amazon chime wont install on Windows machines via ATERA RMM

### ISSUE THREAD

**Issue by lennyfirmin** [tunisiano187/Chocolatey-packages#2987]
Trying to deploy this via Atera RMM product for Windows machine fails
Please note appears to work ok for MAC's

Gives a false positive when installing on Windows saying has deployed but nothing installs. I have tried the --force options this too fails

LOG BELOW

Nothing to change. Config already set.
Installing the following packages:
amazon-chime
By installing you accept licenses for the packages.
amazon-chime v4.39.10239.1 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

Chocolatey installed 0/1 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - amazon-chime - amazon-chime v4.39.10239.1 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.

**Comment by tunisiano187** [comment]
![image](https://user-images.githubusercontent.com/6095739/121784901-06e42200-cbb7-11eb-8384-dbf75a5ecd93.png)
Juste tested, and it's OK for me... I don't know where the problem can be... sorry
