### ISSUE TITLE
[Bug] hash fail with deepl installer 

### ISSUE THREAD

**Issue by x0rld** [tunisiano187/Chocolatey-packages#2988]
**Describe the bug**
I tried to install deepl with your package but the hash doesn't match

**To Reproduce**
1. `choco install deepl`
2. an error will appear when the hashes are checked 

**Expected behavior**
install deepl
**Screenshots**
![image](https://user-images.githubusercontent.com/45242856/120821056-6ad26f00-c555-11eb-91f5-c94228b3dc06.png)

**Desktop:**
 - OS: Windows 10
 - Version 21H1

**Comment by tunisiano187** [comment]
Should be updated soon
