### ISSUE TITLE
[Bug] Bonjour install fails

### ISSUE THREAD

**Issue by hybras** [tunisiano187/Chocolatey-packages#2994]
**Describe the bug**
Installation fails. I am able to installed bonjour 2 using [apple's installer](https://support.apple.com/kb/dl999?locale=en_US)

**To Reproduce**
`choco install bonjour`
` choco install bonjour --version 2.0.2.0`

**Expected behavior**
Installation works

**Console Output**
```
WARNING: MSI could not be found - it is possibly corrupt or not an MSI at all. If it was downloaded and the MSI is less than 30K, try opening it in an editor like Notepad++ as it is likely HTML. This is most likely an issue with the 'bonjour' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly.
ERROR: Running ["C:\WINDOWS\System32\msiexec.exe" /i "C:\Users\varun\AppData\Local\Temp\chocolatey\Bonjour64.msi" /qn /norestart /l*v "C:\Users\varun\AppData\Local\Temp\chocolatey\bonjour.3.1.0.2.MsiInstall.log" ] was not successful. Exit c If it was downloaded and the MSI is less than 30K, try opening it in an editor like Notepad++ as it is likely HTML. This is most likely an issue with the 'bonjour' package and not with Chocolatey itself. Please follow up with the package maintainer(s) directly..
The install of bonjour was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\bonjour\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - bonjour (exited 1619) - Error while running 'C:\ProgramData\chocolatey\lib\bonjour\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Failed with both v2, v3

**Comment by tunisiano187** [comment]
Yes

Le dim. 4 juil. 2021 à 05:08, stale[bot] ***@***.***> a
écrit :

**Comment by hybras** [comment]
What can I do to help? Debugging? Research? Manual install? Logs?

**Comment by hybras** [comment]
Manually running [the installer](https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/bonjour/tools/chocolateyinstall.ps1#L11) worked btw, so I assume there's some metadata that's wrong? IDK anything about choco packaging / manifests

**Comment by tunisiano187** [comment]
I need to look deeper into it, but currently missing time sorry, i'll try to make it work asap
