### ISSUE TITLE
[Update Request] windowsfirewallcontrol

### ISSUE THREAD

**Issue by thefinalwolf** [tunisiano187/Chocolatey-packages#2996]
![2021-07-05_091158](https://user-images.githubusercontent.com/9045213/124498656-8e195580-dd71-11eb-9cd8-2ff55c8da0d3.png)
<---
Type the name of the package in the title
Before submitting please check if the package is in this git
--->

**6.5.0.0**
Give the version that should be available.

**Comment by thefinalwolf** [comment]
> 
> 
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

Sorry, don't know why and don't have the time/energy to learn Chocolatey.
Simply passed by to bring visibility since I so happened to notice.

**Comment by tunisiano187** [comment]
I'll take a look asap
