### ISSUE TITLE
[Update Request] Skype

### ISSUE THREAD

**Issue by NoN-Crying** [tunisiano187/Chocolatey-packages#3005]
Hi,

There are listed known issues with this package:
- Skype automatically starts after installation (no known way to disable it yet)
- A desktop shortcut is automatically created.

The first one is really annoying, as it prevents silent installation with chocolatey to be executed. For this reason it is actually better to use MSI installer instead of EXE. The latest version is always available via https://go.skype.com/msi-download
If using /passive or /quiet switch, it wont automatically run Skype after the installation, thus releasing the command line instead of waiting for user to quit skype or Ctrl-C. Please consider to use MSI installer for distribution of this package instead of EXE.

Thanks in advance!
Ilya

**Comment by tunisiano187** [comment]
Sorry for the delay, i'll take a look tommorrow

**Comment by tunisiano187** [comment]
After looking, i think i'll need to add autohotkey action for this... 
i'll see tomorrow...

**Comment by tunisiano187** [comment]
update sent to the community repository.
we'll wait for merge and the next version of skype to be applyied
