### ISSUE TITLE
[Bug] BOINC wrongly uses unstable release

### ISSUE THREAD

**Issue by rugk** [tunisiano187/Chocolatey-packages#3006]
**Describe the bug**
If you iinstall [Boinc](https://community.chocolatey.org/packages/boinc) it seems to accidentally use some pre-release debug build instead of the official stable/release one.

**Steps To Reproduce**
1. Install from/with chocolately: https://community.chocolatey.org/packages/boinc/7.16.16.20201101
   I used the Chocolately GUI, and it automatically installed such a pre-release. I never wanted that. I wanted a stable version.
2. Start,

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/11966684/129080642-d967a2ac-919d-4bf6-b9cc-2adb319fc36a.png)

If you click "Continue", you just seem to get more erros, here is the one after that past one:
![image](https://user-images.githubusercontent.com/11966684/129080891-b5213153-6860-43e7-9638-367f697d4ed0.png)

**System Information**
 - OS: Windows 10 Build 19042
 - BOINC Version: 7.16.16.20201101 apparently

**Additional context**
N/A

Also:
* should such debug checks even be enabled 
* IMHO, if you can, you should provide a way to copy the long text/error messages there. It's hard to report a bug otherwise, or you can only do so as I did with a screenshot

**Edit:** I admit after clicking seemingly 10 times, I can see a GUI :laughing: 

----

Originally reported upstream as https://github.com/BOINC/boinc/issues/4504

**Comment by jwfxpr** [comment]
In the relevant [update.ps1](https://github.com/tunisiano187/Chocolatey-packages/blob/43e32de5c6318228e0d16a675b042a0536e7c891/automatic/boinc/update.ps1) for BOINC, the direct download directory is used to discover the most recent published version for updating the package:

https://github.com/tunisiano187/Chocolatey-packages/blob/43e32de5c6318228e0d16a675b042a0536e7c891/automatic/boinc/update.ps1#L4

This is what's led to an unstable version being selected for the package:

https://github.com/tunisiano187/Chocolatey-packages/blob/f24d0afdf1b99b51ed94af19efe527b276bf5086/automatic/boinc/tools/chocolateyInstall.ps1#L5

The correct release page is [here](https://boinc.berkeley.edu/download.php), which identifies the current stable 64 bit version as `https://boinc.berkeley.edu/dl/boinc_7.16.11_windows_x86_64.exe`.

I'll submit a PR to correct the URL used for detecting version updates and roll back the package to the stable boinc client. Hopefully the PR will be merged in some reasonable time frame.

**Comment by tunisiano187** [comment]
Should be OK in a few
