### ISSUE TITLE
[Update Request] Redshift-Tray

### ISSUE THREAD

**Issue by BrandonKMLee** [tunisiano187/Chocolatey-packages#3007]
https://github.com/tunisiano187/Chocolatey-packages/tree/master/automatic/rstray

**Version requested**
https://github.com/ltGuillaume/Redshift-Tray/releases/tag/2.1.0

**Comment by jwfxpr** [comment]
An updated package for version 2.1.0 of Redshift-Tray has been submitted, however it is currently [in moderation](https://community.chocolatey.org/packages/rstray/2.1.0) as it was flagged as containing a possible virus. This is a known issue with Redshift-Tray, as noted in the release notes in your link above, and so the package is awaiting a moderator to manually approve it.

**Comment by tunisiano187** [comment]
I don't understand, but the package is flagged on Virustotal, i'll check with @ItGuillaume

**Comment by tunisiano187** [comment]
Answered on community.chocolatey, i'll wait for approval
