### ISSUE TITLE
[Bug] AU does not update WinMerge correctly

### ISSUE THREAD

**Issue by BinToss** [tunisiano187/Chocolatey-packages#3009]
**Describe the bug**
```
Downloading WinMerge 64 bit
  from 'https://github.com/WinMerge/winmerge/releases/download/v2.16.12/WinMerge-2.16.12-Setup.exe'
```
Caused by https://github.com/tunisiano187/Chocolatey-packages/blob/75fbb815ed1c7d07c547bdbb85426d38826a7d42/automatic/winmerge/tools/chocolateyInstall.ps1#L3-L9

The AU script is writing the...
- ARM64 URL to the x86 variable
- x86 URL to the x64 variable

It should be writing the following...
32-bit = https://github.com/WinMerge/winmerge/releases/download/v2.16.12/WinMerge-2.16.12-Setup.exe
64-bit = https://github.com/WinMerge/winmerge/releases/download/v2.16.12/WinMerge-2.16.12-x64-Setup.exe

I was wondering why WinMerge stated it was the 32-bit version.

**Comment by jwfxpr** [comment]
It seems like you're trying to install, 2.16.12, however the lines you've linked to in the `chocolateyInsta.ps1` script are for [the 2.16.14 package](https://community.chocolatey.org/packages/winmerge/2.16.14) which was submitted to chocolately on 26 July.

This continues an unresolved bug that there doesn't seem to have been any attempt to resolve since the 2.16.12 package was submitted in May.

Refer multiple related issues: #3008, #3004, #3001, #2999, #2983, and PR #3000.

@tunisiano187, is there something preventing this issue from being resolved?

**Comment by gep13** [comment]
@BinToss @jwfxpr are either of you in a position to raise a PR to address this problem?

That might help to speed things up in terms of getting this addressed.

**Comment by JPRuskin** [comment]
Looking at it, I can see the problem - it's doing a select 2 (which is a problem now ARM64 is available, from 2.16.12 and onward), and is perhaps a bit naïve about assuming they'll always be in the right order:

```powershell
$installer = ((Invoke-WebRequest -Uri $releases -UseBasicParsing).Links | Where-Object {$_.href -match ".exe$"} | Where-Object {$_.href -notmatch "PerUser"} | Select-Object -First 2 | Sort-Object ).href
    $url32 = "https://github.com$($installer[1])";
	$url64 = "https://github.com$($installer[0])";
```

Current top three results are:
![image](https://user-images.githubusercontent.com/1975761/130041785-beeaadfd-9ccf-47d4-9c49-2619c5e28d9b.png)

If we didn't want to get too complex (and assume links will always be in descending order by version), we could use something like:

```powershell
$installers = ((Invoke-WebRequest -Uri $releases -UseBasicParsing).Links | Where-Object {$_.href -match ".exe$"} | Where-Object {$_.href -notmatch "PerUser"}).href
$url32 = $installers.Where({$_ -match "(?<!64)-Setup\.exe$"}, 1)
$url64 = $installers.Where({$_ -like "*-X64-Setup.exe"}, 1)
```

**Comment by jwfxpr** [comment]
@gep13, #3000 was an attempt (not by me) to fix the issue, but this and other contributions to this repository seem to be blocked by some AppVeyorBot exception or misconfiguration. The original author of the PR withdrew it as a result, with explanation at #3001.

The solution put forward in #3000 is valid, as far as I can tell. At any time this fix can be applied by @tunisiano187. No comment, response, nor action from the repository owner has been evident on any of these issues or the PR.

If submitting a PR were going to resolve this quickly, it would have been so resolved many months ago.

**Comment by gep13** [comment]
@jwfxpr I have reached out to @tunisiano187 via a couple of other communication channels, and hopefully we will hear back from him soon.

If not, are you interested in helping with the maintenance of this package?

**Comment by jwfxpr** [comment]
@gep13 no, personally I'm not really in a position to take that on, I don't have much knowledge about chocolatey internals nor the available attention to come to grips with it/keep abreast of it.

**Comment by jwfxpr** [comment]
> Apologies to @jwfxpr - I didn't spot the PR on the list of issues.

None necessary @JPRuskin! 😊

**Comment by tunisiano187** [comment]
Hello, sorry for the delay, i'll take a look at it

**Comment by tunisiano187** [comment]
Updated
