### ISSUE TITLE
[Update Request] windjview

### ISSUE THREAD

**Issue by TakataSanshiro** [tunisiano187/Chocolatey-packages#3033]
<---
windjview
--->

**Version requested**
2.1

with the new checksum.
It looks like, you forgot to push the version 2.1.0.20210612.
https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/windjview/windjview.nuspec
https://github.com/tunisiano187/Chocolatey-packages/issues/2982
https://community.chocolatey.org/packages/windjview#versionhistory

**Comment by tunisiano187** [comment]
It was rejected, i've updated the error and now waiting for it to be pushed again.
