### ISSUE TITLE
[jbs] checksum error

### ISSUE THREAD

**Issue by jacktose** [tunisiano187/Chocolatey-packages#3050]
[chocolateyinstall.ps1] has `$checksum   = '8f819e316091c11cc6150cb72a234058007ec22928dcd57b5635a4e3e055cc38'`.
Actual SHA-256 of https://dl.johnsadventures.com/SwitcherSetup54.exe is `407670b657a7da9c04711b2d8893faca2dcdb66a82415ef6a75af632b5800a23`.

It's causing `choco upgrade jbs` to fail for me. [Verbose output and log in gist.][gist] I know I installed this version (5.4.0.1) successfully before, so maybe John recompiled it or something?

I figure you'd want AU to fix this, but I can submit a PR to change the checksum if you like.

[chocolateyinstall.ps1]: https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/jbs/tools/chocolateyinstall.ps1
[gist]: https://gist.github.com/jacktose/fe552c5029f2195bc150649a954ea396

**Comment by tunisiano187** [comment]
Update Pushed, but the version is the same... so i had to change the version manually...
