### ISSUE TITLE
[Update Request] warp/21.12.2.0

### ISSUE THREAD

**Issue by johndutchover** [tunisiano187/Chocolatey-packages#3057]
<---
warp
--->

**Version requested**
Version **[2022.2.95.0](https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-windows-1/distribution_groups/release)** should be available please. This would be 22.2.95.0

Thank you.

**Comment by tunisiano187** [comment]
Hello, it just been accepted this morning
Have a nice day
