### ISSUE TITLE
[Update Request] Voicemod

### ISSUE THREAD

**Issue by AndrewIsBest69** [tunisiano187/Chocolatey-packages#3062]
2.27, currently on 2.26

**Comment by tunisiano187** [comment]
Hello, the download link on their website gives me the 2.26.0.1 as it is on the repository, do you have another link ?

**Comment by AndrewIsBest69** [comment]
I don't have I direct link, but it states 2.27 as the newest version in the changelog here: https://www.voicemod.net/changelog/

**Comment by tunisiano187** [comment]
indeed, i think they forgot to update the version number in the package (seems 2.26.0.1 was a beta number), but the link is OK, so it should be the same version.
