### ISSUE TITLE
[Update request] windowsfirewallcontrol package is 6.4.0.0 - up to date is 6.8.1.0

### ISSUE THREAD

**Issue by sir-harlekin** [tunisiano187/Chocolatey-packages#3063]
Please update. Thx! 

https://www.binisoft.org/wfc

https://www.binisoft.org/download/wfc6setup.exe

**Comment by tunisiano187** [comment]
Working on, it seems that the repository refuse my package... 
More informations here : https://gist.github.com/tunisiano187/7032dea203873812b435f152ee3794bf/2a75c0ca96b9464cdc8f737b14c71311244f59a2#windowsfirewallcontrol

**Comment by tunisiano187** [comment]
Done.
