### ISSUE TITLE
[Update Request] SD-Card-formatter

### ISSUE THREAD

**Issue by jenderek** [tunisiano187/Chocolatey-packages#3076]
<---
Type the name of the package in the title
Before submitting please check if the package is in this git
--->
5.0.2
This version should be available.
Current (March 2022) used version by choclatey is 5.0.1.
when i manualy download this package from sdcard.org the archiver name is still SDCardFormatterv5_WinEN.zip,
but inside the installer is now called "SD Card Formatter 5.0.2 Setup EN.exe"

**Comment by tunisiano187** [comment]
Hello, it's already pushed, just waiting for moderation by a chocolatey's moderator.
