### ISSUE TITLE
[Update Request] boinc

### ISSUE THREAD

**Issue by r6d2** [tunisiano187/Chocolatey-packages#3080]
The package source [chocolateyInstall.ps1](https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/boinc/tools/chocolateyInstall.ps1) file in this repo contains a link to the latest version (7.20.2), but chocolatey still installs a different script pointing to 7.16.20. Excuse me if this is an obvious question, but why is that?

**Version requested**
Latest version is: 7.20.2
URL: https://boinc.berkeley.edu/dl/boinc_7.20.2_windows_x86_64.exe

Thanks in advance!

**Comment by tunisiano187** [comment]
The package is waiting to be approved : [boinc 7.20.2](https://community.chocolatey.org/packages/boinc/7.20.2)
Have a nice day
