### ISSUE TITLE
[Bug] Checksum mismatch for creative cloud 

### ISSUE THREAD

**Issue by IDerr** [tunisiano187/Chocolatey-packages#3091]
Hello,
I think that the checksum for creative cloud has changed, and it needs some modification :)

Error - hashes do not match. Actual value was '13BA3A1827B13A3A9C3BBD77F7E59646E185748231EC67E0FF53E0602D788A77'.

Should I just make a PR to change that ?

**Comment by tunisiano187** [comment]
as i don't find any solution to get the number of the last version, it's manual...
i've pushed a correction to force the update
