### ISSUE TITLE
[Bug] SciTE: Install location shown wrong

### ISSUE THREAD

**Issue by stefan-muc** [tunisiano187/Chocolatey-packages#3121]
**Describe the bug**

![image](https://user-images.githubusercontent.com/544335/190626677-28fa4430-2f50-4031-87c7-f5b06bfdb8ac.png)

Install prompt shows `VS Code` as install location as path, but should be `C:\Program Files (x86)\SciTE` (software really is installed there, so just displayed path is wrong).

**To Reproduce**
1. Install SciTE using choclatey
2. While download runs, see VS Code upgrade propmpt, and acnowledge this
3. See wrong path after SciTE is installed

**Desktop:**
 - OS: Windows 10
 - Version 21H2 (OS Build 19044.2006)

**Additional context**
I don't know if this bug is worth effort to dig into it as it foremost is just displaying the wrong path (but installing in correct location), and might be difficult to reproduce.
As I don't know what else can go wrong if this is not looked into (e.g. SciTE install failing, but cocolatey uses "installed successfully" result from VS Code update), I rather report this as issue. 

Decide yourself how to handle it.

**Comment by tunisiano187** [comment]
The installation path is showed by chocolatey itself, not my script.
To be honnest, i don't know where they get it... so i won't e able to solve this.
Have a nice day.
