### ISSUE TITLE
[Update Request] opus-tools

### ISSUE THREAD

**Issue by cannona** [tunisiano187/Chocolatey-packages#3132]
**Version requested**
0.2 compiled with Libopus 1.3

It looks like the version available via this script was compiled with a release candidate of libopus 1.3, where as the current version available to download from https://opus-codec.org/downloads/ was compiled with the post-release version.

**Comment by tunisiano187** [comment]
Thank you for the information.
I've sent an update to the repository, it should be pushed soon to chocolatey.

Have a nice day
