### ISSUE TITLE
[Bug] DS4Windows package deletes the program folder making portable installs impossible

### ISSUE THREAD

**Issue by kwencel** [tunisiano187/Chocolatey-packages#3208]
# Problem description
Line 12 of the chocolateyInstall.ps1 script:
```
ls $toolsPath\* | ? { $_.PSISContainer } | rm -Recurse -Force #remove older package dirs
```
fully deletes the DS4Windows installation folder before installing the updated version.

This prevents use of the portable mode (DS4Windows on the first run asks you whether you want to keep the settings in the AppData or the installation directory). Even if I select portable mode, the next time the DS4Windows package is updated, it will remove the installation folder, which also contains my settings.

# Proposed solution:
Do not wipe the installation folder during updates. Just unpacking the ZIP and overriding everything that is conflicting should work as well and won't prevent the package users from enjoying the portable mode of DS4Windows.

**Comment by tunisiano187** [comment]
Ok, it will be in the next update
