### ISSUE TITLE
[Features] Transmission Pre-release

### ISSUE THREAD

**Issue by maxprehl** [tunisiano187/Chocolatey-packages#3217]
**Is your feature request related to a problem? Please describe.**
The Transmission bittorrent client recently (Oct. 2022) released a public beta: [transmission-4.0.0-beta.1](https://github.com/transmission/transmission/releases/tag/4.0.0-beta.1)

**Describe the solution you'd like**
I'd love if you could create a pre-release package so it can be installed using "choco --pre"

**Describe alternatives you've considered**
Obviously you could update the main package to the 4.0 release, but I think the Transmission folks have made it pretty clear that it's still a beta build.

**Additional context**
To be honest, I wish I could provide more details about creating pre-release packages with chocolatey, but I hit quite the dead end searching on their site.  

I did find an example though, this [Visual Studio](https://community.chocolatey.org/packages/visualstudio2022professional-preview/117.5.0.10000-preview1} package is listed as a prerelease.

**Comment by tunisiano187** [comment]
Partly working, i'll try to get the solution if they had a beta.2 or anything else.

**Comment by maxprehl** [comment]
Just installed!  Thank you so much!  🚀

**Comment by tunisiano187** [comment]
You're welcome.
