### ISSUE TITLE
[Bug] New release of FreePlane

### ISSUE THREAD

**Issue by wichmann** [tunisiano187/Chocolatey-packages#3255]
**Describe the bug**
FreePlane released a new version (1.10.6) and the old file `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/Freeplane-Setup-with-Java-1.10.5.exe/download` is no longer available.

**To Reproduce**
1. Execute `choco install freeplane`

**Expected behavior**
Installation of the newest version of FreePlane.

**Comment by tunisiano187** [comment]
Update sent, the package will be avilable soon, but if you need it quicker, don't hesitate to 
```Powershell
choco upgrade freeplane -y --version="'1.10.6'"
```

Have a nice day
