### ISSUE TITLE
[Update Request] snes9x

### ISSUE THREAD

**Issue by koitsu** [tunisiano187/Chocolatey-packages#3267]
A few things:

* SNES9x 1.61 has been out for almost 9 months: https://github.com/snes9xgit/snes9x/releases .  The team tends to use GitHub now for releases, not so much the old German website
* https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/snes9x/tools/chocolateyInstall.ps1 currently states that the 64-bit build will work on x86 (32-bit), which is incorrect.  You want [snes9x-1.61-win32.zip](https://github.com/snes9xgit/snes9x/releases/download/1.61/snes9x-1.61-win32.zip) for x86, and [snes9x-1.61-win32-x64.zip](https://github.com/snes9xgit/snes9x/releases/download/1.61/snes9x-1.61-win32-x64.zip) for x64.

If you'd prefer a PR for these changes, I can submit one, just let me know.

**Comment by tunisiano187** [comment]
Pushed
