### ISSUE TITLE
[Update Request] automatic/nano-win/tools/chocolateyInstall.ps1

### ISSUE THREAD

**Issue by Ragos81** [tunisiano187/Chocolatey-packages#3283]
<---
automatic/nano-win/tools/chocolateyInstall.ps1
--->
```
$url            = 'https://files.lhmouse.com/nano-win/nano-win_10156_v7.1-13-ga4fc06579.7z'
$checksum       = 'cacc06d4f97c49f13a06c6281f29b4e76eaf820f5081a78b26acf9d1c647d603'
```

the file is not existing, instead it should be:

```
$url            = 'https://files.lhmouse.com/nano-win/nano-win_10155_v7.1-12-g14f292a7c.7z'
$checksum       = 'DCE659505C33F6DEF27048D44D5998DCBE70AE4361C55FE32398AF33BC83682E'
```
(File added or changed on 2023-01-13 16:12:27)

**Comment by djismgaming** [comment]
Installing nano or nano-win brings choco to an error because the file nano-win_10156_v7.1-13-ga4fc06579.7z does not exist although it's approved on the packages in the repo. (https://community.chocolatey.org/packages/nano-win#files)

**Comment by tunisiano187** [comment]
Done
