### ISSUE TITLE
[Features] (winmerge) Don't install shell extension by package parameter

### ISSUE THREAD

**Issue by stefan-muc** [tunisiano187/Chocolatey-packages#3291]
**Is your feature request related to a problem? Please describe.**
After each update of the WinMerge package through chocolatey, the WinMerge shell extension is installed again.
I don't like the shell extension as access key "w" from "_W_inMerge" collides with the "w" in "Ne_w_" which I use more frequently

**Describe the solution you'd like**
I'd like to see a package parameter that I can set during install so the installer won't install the shell extension anymore and have this documented in package description.
I just know that Chocolatey supports Package Parameters: https://docs.chocolatey.org/en-us/guides/create/parse-packageparameters-argument but I don't know if WinMerge installer supports an argument to not install the shell extension

**Describe alternatives you've considered**
Manually uninstall the shell extension after each update - just a workaround.

**Additional context**

**Comment by tunisiano187** [comment]
Hello,
sorry, I've searched on the net, but did not find any solution to add an argument about the shell extension.
