### ISSUE TITLE
[Bug] After update to the latest version, Freeplane is not starting.

### ISSUE THREAD

**Issue by abhishekbarua** [tunisiano187/Chocolatey-packages#3302]
**Describe the bug**
After update to the latest version, Freeplane is not starting. My jdk version is the latest openjdk available through choolatey.

**To Reproduce**
1. Click the Freeplane icon on the desktop.

**Expected behavior**
The program should start.

Windows 11 build 22621.1702

**Additional context**
If we try the freeplane.bat command,

it reports this:
![image](https://github.com/tunisiano187/Chocolatey-packages/assets/7071873/3b61a10a-a949-456e-acfa-2de550bb3aa0)

**Comment by l-e-e-o** [comment]
This seems to be a Freeplane bug if you run it with Java 20 (which is what you get with `choco install openjdk`). Freeplane currently only supports Java 11 - 17.

Nevertheless, an appropriate JDK should be added as a dependency to this package as it currently does not install Java at all.

**Comment by tunisiano187** [comment]
Should be OK in the next update.
i forced the v17
