### ISSUE TITLE
[Bug] nano crashed with Chinese IME

### ISSUE THREAD

**Issue by NightFurySL2001** [tunisiano187/Chocolatey-packages#3309]
**Describe the bug**
The nano version released here crashes when I try to input Chinese using Chinese IME, or pasting Chinese characters into nano. It force closes the whole command line.

**To Reproduce**
1. Open nano in Terminal
2. Choose a Chinese IME
3. Start typing, or copy paste these characters: `你好` (hello in Chinese)
4. The whole terminal crashes and force quit.

**Expected behavior**

**Screenshots**
![image](https://github.com/tunisiano187/Chocolatey-packages/assets/33471049/28a0d306-4523-4373-a2f5-8b426d3241d9)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2 Build 19045
 - Version nano v7.2-25-g44c0d924b

**Additional context**
The version released on scoop (source from https://github.com/okibcn/nano-for-windows) does not have this problem.

**Comment by tunisiano187** [comment]
Hello, i need to use official installer, not a fork, so the user should pull the changes to the official repository.
Have a nice day

**Comment by NightFurySL2001** [comment]
Where is the official installer source from? The [official nano package](https://nano-editor.org/) does not offer a Windows package AFAIK and this is probably also using a fork version.

**Comment by NightFurySL2001** [comment]
Is there any reason to use the lhmouse package which does not build with UTF-8 option (https://github.com/lhmouse/nano-win/issues/35, https://github.com/lhmouse/nano-win/issues/46#issuecomment-1383152598) over okibcn package? I would be willing to help migrate over as okibcn's package is better in terms of UTF-8 and globalisation support.

**Comment by NightFurySL2001** [comment]
I hope you noticed it, but the package of nano-win now points to a VPN instead of any of the nano packages.

https://github.com/tunisiano187/Chocolatey-packages/commit/deb6cf45e2fb392069d921ec7fe2201795974dbd
![image](https://github.com/tunisiano187/Chocolatey-packages/assets/33471049/19e6f9d1-fce1-426b-a9a0-7f4fb9318c80)

https://github.com/tunisiano187/Chocolatey-packages/blob/a324f08f0abc94064c7e678844b2908b37d5870e/automatic/nano-win/tools/chocolateyInstall.ps1#L3
![image](https://github.com/tunisiano187/Chocolatey-packages/assets/33471049/781c5e40-ff3e-44ed-a57a-2bda99e1a354)

**Comment by tunisiano187** [comment]
Seems not

**Comment by NightFurySL2001** [comment]
The ps1 script is still incorrect:
https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/nano-win/tools/chocolateyInstall.ps1

https://github.com/tunisiano187/Chocolatey-packages/blob/db7583b764ac4eab381cb520f57addd2e2b2e993/automatic/nano-win/tools/chocolateyInstall.ps1#L3

Also, this is still not using the okiban nano version (https://github.com/okibcn/nano-for-windows/tree/master). I'm not sure if you would like to switch the source over. If it's ok to switch the source, I can try to create a pull request.

**Comment by tunisiano187** [comment]
Hello,
You can, but just with the upload. Ps1, and setting version to 0.0 in the nuspec.
I won't be able to update it this week, but a PR can 😉
Thank you

**Comment by NightFurySL2001** [comment]
May I ask how long usually does it take for the chocolatey site to update?

**Comment by NightFurySL2001** [comment]
@tunisiano187 May I ask what is the current progress of nano on Chocolatey? The package is still not updated on the site.

**Comment by tunisiano187** [comment]
I cannot update it as the versions are higher than the current one

**Comment by tunisiano187** [comment]
You can see the test to push it here https://gist.github.com/tunisiano187/7032dea203873812b435f152ee3794bf/dadf666067e000747148f6949fc1cca315cfb865#nano

**Comment by NightFurySL2001** [comment]
Hmmm… damn. The version number clashed with what is released already. Not sure why that happened though (should be 7.2.22.1 for both nano and nano-win, but nano-win updated to 7.2.36 which is the lhmouse version).

Is it possible to remove the previous versions of nano package and republish it?

**Comment by tunisiano187** [comment]
No, as the package is already validated, the rule is it can't be updated anymore

**Comment by NightFurySL2001** [comment]
Question: why is nano (https://github.com/tunisiano187/Chocolatey-packages/blob/master/automatic/nano/nano.nuspec) on 7.2.36 when nano-win is on 7.2.22.1? 

It seems that the okibcn version of 7.2-22.1 did get uploaded to site: `choco install nano-win --version=7.2.22.1` downloads the okibcn version.

**Comment by tunisiano187** [comment]
they are both at 7.2.36, i don't understand your question ?

**Comment by NightFurySL2001** [comment]
Sorry, I mean that okibcn's nano v7.2-22.1 is actually uploaded to choco `nano-win` (https://community.chocolatey.org/packages/nano-win/7.2.22.1), but the original lhmouse's version has a higher number (7.2.36) meaning that the lhmouse version is still recognised as the latest version.

`nano` referenced only the newest version of `nano-win` which is 7.2.36, and that's the lhmouse version.

I will try to ask the site admin on how to resolve this issue such that we can use the okibcn's version as the latest.

**Comment by tunisiano187** [comment]
The only solution is to have to create a new package that will have a new version, but... except nanowin directly... i don't see another solution.
