### ISSUE TITLE
[Update Request] Warp/23.3.450.0 

### ISSUE THREAD

**Issue by pvpham** [tunisiano187/Chocolatey-packages#3310]
**Version Requested**

Warp Version [23.7.7](https://install.appcenter.ms/orgs/cloudflare/apps/1.1.1.1-windows-1/distribution_groups/release) should be available.

**Comment by tunisiano187** [comment]
Hello, it's been sent, i've requested a retry of the test.

**Comment by tunisiano187** [comment]
Updated
