### ISSUE TITLE
[Bug] DDU installation script broken

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [tunisiano187/Chocolatey-packages#3313]
**Describe the bug**

DDU install errors with 
`ERROR: A parameter cannot be found that matches parameter name 'Folder'.`

Caused by usage of nonexistent `-Folder` parameter with `Get-ChildItem` 
https://github.com/tunisiano187/Chocolatey-packages/blob/4e549ff9a4b60882674cca7480b139425d3d3292/automatic/ddu/tools/chocolateyInstall.ps1#L24

**To Reproduce**
1. `choco install ddu`

**Expected behavior**

The `ddu` package installs without error.

**Screenshots**

![image](https://github.com/tunisiano187/Chocolatey-packages/assets/38865330/3ec417d3-b494-4ef0-a4a3-e1d0604c10e9)

**Desktop (please complete the following information):**
 - OS: Win 10 22H2
 - Version 18.0.6.2023072101

**Additional context**
Reoccurrence of https://github.com/tunisiano187/Chocolatey-packages/issues/3282

**Comment by TheCakeIsNaOH** [comment]
@tunisiano187 I'm not seeing a new fix version on CCR

**Comment by tunisiano187** [comment]
Hi,
i've updated the script, it should be sent in the next ci
