### ISSUE TITLE
freeplane 1.11.5 liberica jre dependency outdated causing conflict

### ISSUE THREAD

**Issue by Furgelnod** [tunisiano187/Chocolatey-packages#3315]
Liberica JRE has been updated to 17.0.8 the script for freeplane is dependent on 17.0.7 specifically. If I run `choco upgrade all` the JRE gets updated, then all other choco commands are blocked due to "One or more unresolved package dependency constraints detected in the Chocolatey lib folder. All dependency constraints must be resolved to add or update packages." Should the script not use `>= 17.0.7` instead of `= 17.0.7` ? The only way I got things functioning was by uninstalling that JRE which of course renders FreePlane non-functional.

**Comment by tunisiano187** [comment]
Done

**Comment by dznz** [comment]
@tunisiano187 - does the nuspec file need a version bump in order to trigger a rebuild/republish to the Chocolatey gallery? I note that https://community.chocolatey.org/packages/FreePlane#dependencies indicates the published package is still on JRE `v17.0.7`.
