### ISSUE TITLE
[Bug] (ds4windows) dotnet-desktopruntime dependency not installed

### ISSUE THREAD

**Issue by Destroy666x** [tunisiano187/Chocolatey-packages#3329]
**Describe the bug**
Recent versions of DS4Windows require [`dotnet-desktopruntime` ](https://community.chocolatey.org/packages/dotnet-desktopruntime)version 8. It's not installed as a dependency by choco. Instead it installs older `dotnet-6.0-desktopruntime`.

**To Reproduce**
1. Install `ds4windows` package
2. Open ds4windows.exe
3. It'll ask you to install .NET Desktop Runtime 8.0

**Expected behavior**
Dependency should be automatically installed.

**Screenshots**
\-

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 22H2

**Comment by tunisiano187** [comment]
correction pushed, I'll wait for the upload process
