### ISSUE TITLE
Error While Updating Arduino Choco Package

### ISSUE THREAD

**Issue by PitchAbyss** [tunisiano187/Chocolatey-packages#3336]
![Screenshot_10](https://github.com/tunisiano187/Chocolatey-packages/assets/13099434/8f436ce3-a2ab-4726-a8f9-7099abc90f8e)

![Screenshot_11](https://github.com/tunisiano187/Chocolatey-packages/assets/13099434/453fca51-6296-4cde-bfc5-b7aefc4e00e8)

**Comment by tunisiano187** [comment]
I've added a uninstallation script before the install, it will be available in the next version

**Comment by PitchAbyss** [comment]
> I've added a uninstallation script before the install, it will be available in the next version

Thankyou so much
