### ISSUE TITLE
Warp Chocolatey Package Install Error

### ISSUE THREAD

**Issue by PitchAbyss** [tunisiano187/Chocolatey-packages#3410]
hi Please see the error i get while installing or upgrading warp

![Screenshot_2](https://github.com/tunisiano187/Chocolatey-packages/assets/13099434/d2d1b593-d7c2-4243-a2a8-bbf8a834adea)

**Comment by tunisiano187** [comment]
Hi, indeed, they seems to already have updated their installer.
I'll push a new one

**Comment by PitchAbyss** [comment]
> Hi, indeed, they seems to already have updated their installer.
> I'll push a new one

Thanks would i need to uninstall and reinstall or upgrade normall i would do

**Comment by tunisiano187** [comment]
no, it even seems that downloading the file directly isn't possible...
i think that's a problem on cloudflare's side.
i assume you still have the previous version, you can still use it, and the upgrade will be OK
i there is a change, i'll update the version number, so chocolatey will update automatically.

**Comment by PitchAbyss** [comment]
> no, it even seems that downloading the file directly isn't possible... i think that's a problem on cloudflare's side. i assume you still have the previous version, you can still use it, and the upgrade will be OK if there is a change, i'll update the version number, so chocolatey will update automatically.

this error was when i did choco upgrade <package>

**Comment by tunisiano187** [comment]
Yes, but you can retry in a day, maybe the problem will be solved (chocolatey redownload the packae after some times if it changes), as that's not a checksum error.
If there is a newer version available when it come back available, my ci will automatically push a newer version, and as soon as the package is approved (it's automated as the package is a trusted one, so if no problem is found, it will be approved quickly) the newer version will be taken by your client and upgrade the sofware on your computer.

**Comment by tunisiano187** [comment]
i'm closing the request as the problem is on the server side, but if you see a newer version with the same problem, don't hesitate to comment here, it will reopen the issue.
Have a nice day.

**Comment by PitchAbyss** [comment]
> i'm closing the request as the problem is on the server side, but if you see a newer version with the same problem, don't hesitate to comment here, it will reopen the issue.
> Have a nice day.

Thanku so much il try after some days and see if issue gets fixed
