### ISSUE TITLE
(winedt) update requested

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/Chocolatey-packages#3418]
([winedt](https://chocolatey.org/packages/winedt)) Outdated and needs to be updated
    [winedt](https://github.com/chocolatey-community/chocolatey-package-requests/issues/1141)

**Comment by romualdginhoux** [comment]
Hello Tunisiano187,
do you have a plan to change the download URL in chocolateyinstall.ps1 for Bonjour Service?
Because since the end of March, "https://support.apple.com/downloads/DL999/en_US/BonjourPSSetup.exe" is pointing to an HTML page.
Regards

**Comment by tunisiano187** [comment]
Hello,
No, i don't find a way to install the latest version.
I've requested son the community git for a new maintainer to take the package as i don't have a solution for it.
You can see it there : https://github.com/chocolatey-community/chocolatey-package-requests/issues/1514

Sorry

**Comment by tunisiano187** [comment]
WinEdt ready, PR to do on dtgm's git
