### ISSUE TITLE
[Bug] Freeplane requires not current jdk

### ISSUE THREAD

**Issue by Furgelnod** [tunisiano187/Chocolatey-packages#3498]
**Describe the bug**
The freeplane script ( automatic/freeplane/freeplane.nuspec ) requires an outdated version of corretto11jdk breaking updates to freeplane and all other packages.

**To Reproduce**
1. ensure that corretto11jdk is already updated to the latest version 11.0.23.91
2. run choco upgrade -y freeplane

**Expected behavior**
The package freeplane to be updated.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
The output running the upgrade is
`Unable to resolve dependency 'corretto11jdk': Unable to resolve dependencies. 'corretto11jdk 11.0.23.91' is not compatible with 'freeplane 1.11.12 constraint: corretto11jdk (= 11.0.22.71)'.`

**Comment by tunisiano187** [comment]
Hello,
I've pushed a correction, but it will only be available on the next update.

Have a nice day
