### ISSUE TITLE
[Bug] Incorrect SHA256 in Bonjour (Install) 3.1.0.3

### ISSUE THREAD

**Issue by briped** [tunisiano187/Chocolatey-packages#3620]
**Describe the bug**

> Error - hashes do not match. Actual value was '9CBAEF01A8E2BE6F4AA68768484268DEF7CA71491B71E56B435D4878DA3232FD'.
> ERROR: Checksum for 'C:\ProgramData\chocolatey\lib\bonjour\tools\itunes.zip' did not meet '541c30b2d72705afe75649f97e3daf677b8576e6e73d6f78f7265a0ded61011f' for checksum type 'SHA256'.

**To Reproduce**
Just attempt to install or upgrade `bonjour` package
`choco install --yes bonjour`

**Expected behavior**
`chocolateyinstall.ps1` should contain the correct SHA256 hash.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 24H2

**Additional context**
Verified that SHA256 hash in chocolateyinstall.ps1 is incorrect, by downloading the file manually and checking the SHA256 hash.
```
$RootPath = (Get-Item -Path .).PSDrive.Root
$TempPath = Join-Path -Path $RootPath -ChildPath 'tmp'
if (!($Temp = [System.IO.DirectoryInfo]$TempPath).Exists) {
    $Temp = New-Item -Force -ItemType Directory -Path $TempPath
}
$OutFile = Join-Path -Path $Temp.FullName -ChildPath 'itunes.zip'
$Url = 'https://www.apple.com/itunes/download/win64'
Invoke-WebRequest -Uri $Url -OutFile $OutFile
(Get-FileHash -Algorithm SHA256 -Path $OutFile).Hash
```
Which at the of writing this is:
`9CBAEF01A8E2BE6F4AA68768484268DEF7CA71491B71E56B435D4878DA3232FD`

[Commented](https://community.chocolatey.org/packages/bonjour#comment-6466608933) on the package on Chocolatey as well.

**Comment by tunisiano187** [comment]
Hello,
The newer version has been pushed.
have a nice day.
