### ISSUE TITLE
[Update Request] CryptSync

### ISSUE THREAD

**Issue by mr-rubbish** [tunisiano187/Chocolatey-packages#3715]
<---
Type the name of the package in the title
Before submitting please check if the package is in this git
--->

1.4.7
Give the version that should be available.

**Comment by tunisiano187** [comment]
Hello, the update has already been sent, it should be available soon.
You can check it here : [https://chocolatey.org/packages/cryptsync/1.4.7](https://chocolatey.org/packages/cryptsync/1.4.7)
Have a nice day.
