### ISSUE TITLE
[Bug] Folding At Home does install but is not runnable

### ISSUE THREAD

**Issue by theking2** [tunisiano187/Chocolatey-packages#3751]
**Describe the bug**

**To Reproduce**
1. choco install -y fah
2. Click on 'FAHControl'

**Expected behavior**
FAH interface should start

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version fah-installer_7.6.21_x86.exe

**Comment by tunisiano187** [comment]
Hello,
the installer was still using v7, so i've updated my updater to use the v8.
It should be updated in ! hours.
