### ISSUE TITLE
[Update Request] SNES9x

### ISSUE THREAD

**Issue by mer2329** [tunisiano187/Chocolatey-packages#3767]
not sure how to word this or if this is the right category, but ill try... sorry if i get anything wrong.

the chocolateyGUI shows the package as 1.63.0, installing it, only installs 1.60
![image](https://github.com/tunisiano187/Chocolatey-packages/assets/6768243/c0df901b-0bbf-47f9-8bd9-ebd4a5971425)

but on other sites like emulator zone i can find 1.62.3
which are indeed 1.62.3
![image](https://github.com/tunisiano187/Chocolatey-packages/assets/6768243/6fc91a4b-9877-42f4-9bf4-dba64afb83e8)

edit: also. downloading from the github does give you 1.6.3
![image](https://github.com/tunisiano187/Chocolatey-packages/assets/6768243/7a0b0b87-76cd-41ca-8268-6fa2d0cbe9cb)

**Comment by tunisiano187** [comment]
Hello,
you can see here the download link is from github : https://community.chocolatey.org/packages/snes9x#files
maybe you have multiple version in the folder ?
can you check in %programdata%\chocolatey\lib\snes9x\tools ?

**Comment by mer2329** [comment]
i was reinstalling windows due to a failed mbr to GPT conversion. so there is no chance of files already being there.

**Comment by tunisiano187** [comment]
Weird, i've just tested it in a vagrant test environment and it's OK with version 1.63, so i don't understand your problem.
can you try to do this ?
`choco uninstall -y snes9x
choco cache remove
choco install -y snes9x`

**Comment by mer2329** [comment]
ok, done, not showing in start menu, and im getting a error when i try and run it from `%programdata%\chocolatey\lib\snes9x\tools`
![image](https://github.com/tunisiano187/Chocolatey-packages/assets/6768243/839df57f-2527-45bc-b89c-86c5d19a98a0)

**Comment by tunisiano187** [comment]
can you redo the same, but remove the folder snes9x in 
%programdata%\chocolatey\lib\
%programdata%\chocolatey\lib-bad\
%programdata%\chocolatey\lib-bkp\
before reinstall ?

**Comment by mer2329** [comment]
ok i just did the following, 
ran the uninstall command. 
checked the 3 locations for snes9x folders (none found)
and then cleanded choco, and reinstalled snes9x
and

**Comment by mer2329** [comment]
i used the litterbox part of catbox, its temporary storage. 
https://litter.catbox.moe/z26z8c.zip
file will expire in 3 days
