### ISSUE TITLE
[Bug] Hashcat installed via Chocolatey fails to launch in PowerShell due to incorrect path

### ISSUE THREAD

**Issue by mikhailde** [tunisiano187/Chocolatey-packages#3789]
## Description

After installing Hashcat using Chocolatey on Windows 11, attempting to run the `hashcat` command in PowerShell results in an error. The provided PowerShell script `hashcat.ps1` uses an incorrect path, leading to the failure. Additionally, using a PowerShell script introduces unnecessary overhead.

## **Describe the bug**

The `hashcat.ps1` script, located in `C:\ProgramData\chocolatey\lib\hashcat\tools\hashcat.ps1`, uses the environment variable `$env:ChocolateyToolsLocation` to construct the path to the Hashcat executable. However, this path appears to be incorrect, causing a "path not found" error. Subsequently, the script attempts to execute `.\hashcat64.exe`, which also fails because the working directory is not set correctly. Moreover, relying on a PowerShell script adds unnecessary complexity and potential points of failure.

## **To Reproduce**

1. Install Hashcat using Chocolatey: `choco install hashcat`
2. Close and reopen PowerShell.
3. Run the command: `hashcat`
4. See error:
    ```
    Set-Location : Не удается найти путь "C:\tools\hashcat\", так как он не существует.
    ...
    .\hashcat64.exe : Имя ".\hashcat64.exe" не распознано ...
    ...
    ```

## **Expected behavior**

After installing Hashcat via Chocolatey and running the `hashcat` command in PowerShell, the Hashcat application should launch without errors. Ideally, this should be achieved without relying on a PowerShell script.

## **Desktop:**
 - OS: Windows 11 Home
 - Version: 22631.4037

## **Additional context**

The issue can be resolved by modifying the `hashcat.ps1` script to dynamically find the correct directory containing the `hashcat.exe` executable. The proposed solution uses `Get-ChildItem` to search for a directory matching the pattern `"$env:ChocolateyToolsLocation\hashcat*"` and then uses the `FullName` property to get the complete path.

**Proposed fix in `C:\ProgramData\chocolatey\lib\hashcat\tools\hashcat.ps1`:**

```powershell
$hashcatDir = (Get-ChildItem "$env:ChocolateyToolsLocation\hashcat*" -Directory).FullName

Push-Location $hashcatDir

& ".\hashcat.exe" $args

Pop-Location
```

This fix allows the script to correctly locate and execute the `hashcat.exe` file, regardless of minor variations in the installation path. 

**However, a more robust and efficient solution would be to convert the PowerShell script to an executable using a tool like `ps2exe` and placing it in the default Chocolatey bin directory `C:\ProgramData\chocolatey\bin`.** This would eliminate the overhead of invoking the PowerShell interpreter and provide a more seamless user experience.  This approach would also simplify the execution process and avoid potential issues related to script execution policies.

**Comment by tunisiano187** [comment]
Thank you for the information.
I've updated the script, it should be OK in the next release
