### ISSUE TITLE
[Bug] Spybot Failed Verification Testing

### ISSUE THREAD

**Issue by tunisiano187** [tunisiano187/Chocolatey-packages#9]
https://chocolatey.org/packages/spybot/2.8.68.0

**Comment by tunisiano187** [comment]
https://gist.github.com/60904d581c95449e97929c34cec69e0f

**Comment by tunisiano187** [comment]
AHK needed

**Comment by chtof** [comment]
It looks like it's a know issue since version 2.7: https://forums.spybot.info/showthread.php?77434-Install-Spybot-2-8-67-0-Silent-Mode-Batch&p=484652
